#include "my_led.h"
#include "xil_io.h"
#include "xparameters.h"

int main() {

	int sw;

	while(1) {
		sw = MY_LED_mReadReg(XPAR_SW_BASEADDR, MY_LED_S00_AXI_SLV_REG0_OFFSET);

		if (sw == 0x1){
			MY_LED_mWriteReg(XPAR_MY_LED_0_S00_AXI_BASEADDR, MY_LED_S00_AXI_SLV_REG0_OFFSET, 1);
			MY_LED_mWriteReg(XPAR_MY_LED_0_S00_AXI_BASEADDR, MY_LED_S00_AXI_SLV_REG1_OFFSET, 0);
		}
		if (sw == 0x2){
			MY_LED_mWriteReg(XPAR_MY_LED_0_S00_AXI_BASEADDR, MY_LED_S00_AXI_SLV_REG0_OFFSET, 2);
			MY_LED_mWriteReg(XPAR_MY_LED_0_S00_AXI_BASEADDR, MY_LED_S00_AXI_SLV_REG1_OFFSET, 0);
		}
		if (sw == 0x4){
			MY_LED_mWriteReg(XPAR_MY_LED_0_S00_AXI_BASEADDR, MY_LED_S00_AXI_SLV_REG1_OFFSET, 1);
			MY_LED_mWriteReg(XPAR_MY_LED_0_S00_AXI_BASEADDR, MY_LED_S00_AXI_SLV_REG0_OFFSET, 0);
		}
		if (sw == 0x8){
			MY_LED_mWriteReg(XPAR_MY_LED_0_S00_AXI_BASEADDR, MY_LED_S00_AXI_SLV_REG1_OFFSET, 2);
			MY_LED_mWriteReg(XPAR_MY_LED_0_S00_AXI_BASEADDR, MY_LED_S00_AXI_SLV_REG0_OFFSET, 0);
		}
		if (sw == 0x0) {
			MY_LED_mWriteReg(XPAR_MY_LED_0_S00_AXI_BASEADDR, MY_LED_S00_AXI_SLV_REG1_OFFSET, 0);
			MY_LED_mWriteReg(XPAR_MY_LED_0_S00_AXI_BASEADDR, MY_LED_S00_AXI_SLV_REG0_OFFSET, 0);
		}
	}

	return 0;
}
